name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build JAR using Maven
        working-directory: ./SkillBridge/backend/skillbridge
        run: mvn clean package -DskipTests

      - name: Build and Push Backend
        working-directory: ./SkillBridge/backend/skillbridge
        run: |
          docker build -t vishesh022/springboot-app:latest .
          docker push vishesh022/springboot-app:latest

      - name: Build and Push Frontend
        working-directory: ./SkillBridge/frontend
        run: |
          docker build -t vishesh022/react-app:latest .
          docker push vishesh022/react-app:latest
